# -*- coding: utf-8 -*-
"""Gender&AgeClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLfL0EvIt9xfGPghsad5e5UvYsPg1_lO
"""

import pandas as pd
import datetime as dt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/dataset_800_baris.csv")
df.head()

df = df[['Gender', 'Tanggal_Lahir']]

df.head()

df.info()

group = df.groupby('Gender').count()
group

df['Tanggal_Lahir'] = pd.to_datetime(df['Tanggal_Lahir'], format= '%Y-%m-%d')

hari_ini = dt.datetime.now()
df['usia'] = ((hari_ini - df['Tanggal_Lahir']).dt.days // 365)

df.head()

max_usia = df['usia'].max()
bins = list(range(0, (max_usia // 10 + 2) * 10, 10))
labels = [f"{i}an" for i in bins[:-1]]

df['usia_group'] = pd.cut(df['usia'], bins=bins, labels=labels, right=True)

df_grouped = df.groupby(['Gender', 'usia_group']).size().reset_index(name='count')
print(df_grouped)
jumlah = len(df)
print(f"Jumlah = {jumlah}.")

sns.countplot(data=df, x='usia_group', hue='Gender')
plt.xlabel("Usia Group")
plt.ylabel("Jumlah")
plt.title("Distribusi Gender per Usia")
plt.show()